import { defineConfig, type Plugin, type ViteDevServer } from "vite";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { spawn } from "node:child_process";
import path from "node:path";
import yaml from "js-yaml";

// Dev-only HTTP API backing the tile editor (/editor.html). Reads an asset-forge
// stage source, applies hand-painted cell patches + any newly minted roster tiles,
// then re-runs ONLY that stage's import step so the live game hot-reloads. The
// bridge (build-*-from-authored) is deliberately NOT run — the editor is the
// authoritative hand-tuning layer on top of the auto-generated layout.
//
// The editor is stage-agnostic: every stage with an `assets:stage:<name>` script
// in package.json is editable. Each stage's atlas, columns, dimensions and paths
// are read from its own stage.json + tileset manifest, so nothing here is wired
// to a single region.
const ROOT = process.cwd();

function readJson(rel: string): any {
  return JSON.parse(readFileSync(path.join(ROOT, rel), "utf8"));
}
function writeJson(rel: string, value: unknown): void {
  writeFileSync(path.join(ROOT, rel), JSON.stringify(value, null, 2) + "\n");
}
function readYaml(rel: string): any {
  return yaml.load(readFileSync(path.join(ROOT, rel), "utf8"));
}

// --- Editor "Layers" feature -------------------------------------------------
// Each editable region maps to a runtime FLOOR number + a spawn ZONE id. The
// editor canvas works in tile coords (1:1 with spawns.yaml `at:` coords — all
// floors are authored at their target size, see SCALE_AUTHORED_AT_TARGET in
// build-content.ts), so a clicked cell IS the spawn tile. stage.json carries
// neither floor nor zone, so this small table is the source of truth — it
// mirrors ZONES in src/shared.ts. A stage absent here simply gets no layers.
const STAGE_META: Record<string, { floor: number; zone: string }> = {
  waystone: { floor: 0, zone: "southTown" },
  cemetery: { floor: 1, zone: "cemetery" },
  crypt: { floor: 2, zone: "crypt" },
  northwood: { floor: 3, zone: "woods" },
  northwatch: { floor: 4, zone: "northTown" },
  swamp: { floor: 5, zone: "marsh" },
  "searing-canyon": { floor: 6, zone: "badlands" },
  desert: { floor: 7, zone: "desert" },
  beach: { floor: 8, zone: "beach" },
  jungle: { floor: 9, zone: "jungle" },
  deepmine: { floor: 10, zone: "deepMine" }
};

const SPAWN_OVERLAY_FILE = "content/spawns.editor.yaml";
interface SpawnOverlay {
  monsters: Array<{ type: string; at: { floor: number; x: number; y: number }; zone: string }>;
  removed: Array<{ floor: number; x: number; y: number }>;
}
function readSpawnOverlay(): SpawnOverlay {
  if (!existsSync(path.join(ROOT, SPAWN_OVERLAY_FILE))) return { monsters: [], removed: [] };
  const doc = (readYaml(SPAWN_OVERLAY_FILE) as Partial<SpawnOverlay>) ?? {};
  return { monsters: doc.monsters ?? [], removed: doc.removed ?? [] };
}
// Hand-emit compact, schema-free YAML so the file stays diff-friendly and clearly
// machine-owned. Hand-authored spawns are in spawns.yaml; this file is rewritten
// wholesale by the editor on every spawn save, so it must never be hand-edited.
function writeSpawnOverlay(doc: SpawnOverlay): void {
  const lines = [
    "# AUTO-GENERATED by the stage editor's Spawns layer — DO NOT hand-edit.",
    "# Hand-authored spawns live in spawns.yaml and are never touched here.",
    "# `monsters` are editor placements; `removed` suppresses a spawns.yaml spawn",
    "# at that exact tile (a moved base spawn = one removal + one placement).",
    "# Merged with spawns.yaml at build time by scripts/build-content.ts.",
    ""
  ];
  if (doc.monsters.length) {
    lines.push("monsters:");
    for (const m of doc.monsters) {
      lines.push(`  - { type: ${m.type}, at: { floor: ${m.at.floor}, x: ${m.at.x}, y: ${m.at.y} }, zone: ${m.zone} }`);
    }
  } else {
    lines.push("monsters: []");
  }
  if (doc.removed.length) {
    lines.push("removed:");
    for (const r of doc.removed) lines.push(`  - { floor: ${r.floor}, x: ${r.x}, y: ${r.y} }`);
  } else {
    lines.push("removed: []");
  }
  writeFileSync(path.join(ROOT, SPAWN_OVERLAY_FILE), lines.join("\n") + "\n");
}

// Gathering-node layers (ore, later herbs/fishing). Unlike spawns these are flat
// arrays of nodes with a unique `id`, an `at` tile + an `approach` standing tile,
// and one discriminating field (ore→kind, herb→label). The editor writes ONLY its
// own placements + id-keyed suppressions to a `<base>.editor.yaml`; the merge lives
// in build-content.ts. One config row per node layer keeps the endpoint generic.
interface NodeLayerCfg { base: string; overlay: string; field: string }
const NODE_LAYERS: Record<string, NodeLayerCfg> = {
  ore: { base: "content/mining-nodes.yaml", overlay: "content/mining-nodes.editor.yaml", field: "kind" }
  // herbs: { base: "content/herb-nodes.yaml", overlay: "content/herb-nodes.editor.yaml", field: "label" }
};
interface NodeOverlay {
  nodes: Array<{ id: string; at: { floor: number; x: number; y: number }; approach: { x: number; y: number }; [k: string]: any }>;
  removed: Array<{ floor: number; id: string }>;
}
function readNodeOverlay(rel: string): NodeOverlay {
  if (!existsSync(path.join(ROOT, rel))) return { nodes: [], removed: [] };
  const doc = (yaml.load(readFileSync(path.join(ROOT, rel), "utf8")) as Partial<NodeOverlay>) ?? {};
  return { nodes: doc.nodes ?? [], removed: doc.removed ?? [] };
}
// quote a YAML scalar only when it isn't a bare token (e.g. a herb label with spaces)
const yamlScalar = (v: unknown): string =>
  typeof v === "string" && /^[A-Za-z0-9_-]+$/.test(v) ? v : JSON.stringify(v);
function writeNodeOverlay(rel: string, field: string, doc: NodeOverlay): void {
  const lines = [
    `# AUTO-GENERATED by the stage editor's node layer — DO NOT hand-edit.`,
    `# Hand-authored nodes live in ${path.basename(NODE_LAYERS_BY_OVERLAY[rel]?.base ?? "the base file")} and are never touched here.`,
    `# \`nodes\` are editor placements; \`removed\` suppresses a base node by id.`,
    `# Merged with the base file at build time by scripts/build-content.ts.`,
    ""
  ];
  if (doc.nodes.length) {
    lines.push("nodes:");
    for (const n of doc.nodes) {
      const parts = [`id: ${n.id}`];
      if (n[field] != null) parts.push(`${field}: ${yamlScalar(n[field])}`);
      parts.push(`at: { floor: ${n.at.floor}, x: ${n.at.x}, y: ${n.at.y} }`);
      parts.push(`approach: { x: ${n.approach.x}, y: ${n.approach.y} }`);
      lines.push(`  - { ${parts.join(", ")} }`);
    }
  } else {
    lines.push("nodes: []");
  }
  if (doc.removed.length) {
    lines.push("removed:");
    for (const r of doc.removed) lines.push(`  - { floor: ${r.floor}, id: ${r.id} }`);
  } else {
    lines.push("removed: []");
  }
  writeFileSync(path.join(ROOT, rel), lines.join("\n") + "\n");
}
const NODE_LAYERS_BY_OVERLAY: Record<string, NodeLayerCfg> = Object.fromEntries(
  Object.values(NODE_LAYERS).map((c) => [c.overlay, c])
);

// A stage is editable iff it has a (non-`:check`) `assets:stage:<name>` script.
// We parse the script's own --stage/--vocab args so the source-of-truth stays in
// package.json rather than being duplicated here.
type StageDef = { name: string; stagePath: string; vocabPath: string; script: string };
function discoverStages(): Map<string, StageDef> {
  const pkg = readJson("package.json");
  const out = new Map<string, StageDef>();
  for (const [key, cmd] of Object.entries<string>(pkg.scripts ?? {})) {
    const m = /^assets:stage:([a-z0-9-]+)$/.exec(key);
    const name = m?.[1];
    if (!name) continue; // skips `assets:stage:<name>:check` and unrelated scripts
    const stagePath = /--stage\s+(\S+)/.exec(cmd)?.[1];
    const vocabPath = /--vocab\s+(\S+)/.exec(cmd)?.[1];
    if (!stagePath || !vocabPath) continue;
    out.set(name, { name, stagePath, vocabPath, script: key });
  }
  return out;
}

// Resolve the stage requested via ?stage=, defaulting to northwood for back-compat
// with the old single-stage editor URL. Throws on an unknown stage so callers can
// 404 instead of silently editing the wrong region.
function resolveStage(req: any): StageDef {
  const stages = discoverStages();
  const url = new URL(req.url ?? "", "http://x");
  const want = url.searchParams.get("stage") || "northwood";
  const def = stages.get(want);
  if (!def) throw new Error(`unknown stage '${want}' (have: ${[...stages.keys()].join(", ")})`);
  return def;
}

function body(req: any): Promise<any> {
  return new Promise((resolve, reject) => {
    let raw = "";
    req.on("data", (c: Buffer) => (raw += c));
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : {});
      } catch (e) {
        reject(e);
      }
    });
    req.on("error", reject);
  });
}
function send(res: any, code: number, value: unknown): void {
  res.statusCode = code;
  res.setHeader("content-type", "application/json");
  res.end(JSON.stringify(value));
}

function regenerate(script: string): Promise<{ ok: boolean; log: string }> {
  return new Promise((resolve) => {
    const child = spawn("npm", ["run", script], { cwd: ROOT });
    let log = "";
    child.stdout.on("data", (d) => (log += d));
    child.stderr.on("data", (d) => (log += d));
    child.on("close", (code) => resolve({ ok: code === 0, log }));
    child.on("error", (e) => resolve({ ok: false, log: String(e) }));
  });
}

function editorApi(): Plugin {
  return {
    name: "tib-stage-editor-api",
    apply: "serve",
    configureServer(server: ViteDevServer) {
      // List the editable stages so the editor can offer a switcher.
      server.middlewares.use("/editor/api/stages", (_req, res) => {
        try {
          send(res, 200, { stages: [...discoverStages().keys()].sort() });
        } catch (e) {
          send(res, 500, { error: String(e) });
        }
      });

      server.middlewares.use("/editor/api/state", (req, res) => {
        try {
          const def = resolveStage(req);
          const stage = readJson(def.stagePath);
          const vocab = readJson(def.vocabPath);
          const base = stage.layers.find((l: any) => l.name === "base");
          const fringe = stage.layers.find((l: any) => l.name === "fringe");
          // Atlas + column count come from the stage's own tileset declaration and
          // its manifest, so every region renders against the right sheet.
          const ts = stage.tilesets?.[0] ?? {};
          const atlasName = ts.name ?? stage.name;
          const stageDir = path.dirname(def.stagePath);
          let atlasCols = 24;
          try {
            if (ts.manifest) atlasCols = readJson(path.join(stageDir, ts.manifest)).columns ?? 24;
          } catch { /* manifest optional — fall back to 24 */ }
          // Optional per-stage blob autotile sets (road/water): bitmask→atlas-index
          // tables proposed by tools/classify-*-blobset.py and hand-tuned in place.
          // Absent for stages without one — the editor just omits those auto-tools.
          let blobsets: any[] = [];
          try {
            blobsets = readJson(path.join(stageDir, `${def.name}.blobset.json`)).sets ?? [];
          } catch { /* no blobset for this stage — fine */ }
          // Editor "Layers": for stages mapped to a floor/zone, send the floor's
          // current spawns (base from spawns.yaml minus suppressions, plus editor
          // overlay placements — each tagged with its source) and the monster
          // palette. Stages without a mapping get floor:null → layers disabled.
          const meta = STAGE_META[def.name];
          let floor: number | null = null;
          let zone: string | null = null;
          let editorSpawns: any[] = [];
          let monsterTypes: any[] = [];
          let editorOre: any[] = [];
          let oreKinds: string[] = [];
          if (meta) {
            floor = meta.floor;
            zone = meta.zone;
            const overlay = readSpawnOverlay();
            const removed = new Set(overlay.removed.map((r) => `${r.floor},${r.x},${r.y}`));
            const baseSpawns = (readYaml("content/spawns.yaml")?.monsters ?? []) as any[];
            const base = baseSpawns
              .filter((s) => s.at?.floor === floor && !removed.has(`${s.at.floor},${s.at.x},${s.at.y}`))
              .map((s) => ({ type: s.type, x: s.at.x, y: s.at.y, source: "base" }));
            const over = overlay.monsters
              .filter((s) => s.at?.floor === floor)
              .map((s) => ({ type: s.type, x: s.at.x, y: s.at.y, source: "overlay" }));
            editorSpawns = [...base, ...over];
            monsterTypes = ((readYaml("content/monsters.yaml") as any[]) ?? [])
              .filter((m) => m && m.id)
              .map((m) => ({ id: m.id, name: m.name ?? m.id }));
            // Ore nodes for this floor (base mining-nodes.yaml minus suppressions +
            // editor overlay). Each node ships its at-tile (x/y) and approach (ax/ay).
            const oreCfg = NODE_LAYERS.ore!;
            const oreOv = readNodeOverlay(oreCfg.overlay);
            const removedOre = new Set(oreOv.removed.map((r) => r.id));
            const toOre = (n: any, source: string) => ({
              id: n.id, kind: n.kind ?? "copper", source,
              x: n.at?.x, y: n.at?.y, ax: n.approach?.x, ay: n.approach?.y
            });
            const baseOre = ((readYaml(oreCfg.base) as any[]) ?? [])
              .filter((n) => n.at?.floor === floor && !removedOre.has(n.id))
              .map((n) => toOre(n, "base"));
            const overOre = oreOv.nodes.filter((n) => n.at?.floor === floor).map((n) => toOre(n, "overlay"));
            editorOre = [...baseOre, ...overOre];
            oreKinds = ["copper", "tin", "iron", "coal", "silver", "gold", "mithril", "adamant"];
          }
          send(res, 200, {
            floor,
            zone,
            spawns: editorSpawns,
            monsterTypes,
            ore: editorOre,
            oreKinds,
            name: stage.name,
            cols: stage.cols,
            rows: stage.rows,
            tileSize: stage.tileSize,
            atlasName,
            atlasCols,
            atlasUrl: `/tilesets/${def.name}/${ts.image ?? `${atlasName}.png`}`,
            legend: stage.ascii.legend,
            vocab: vocab.chars,
            ascii: stage.ascii.rows,
            base: base?.data ?? [],
            fringe: fringe?.data ?? null,
            blobsets,
            rotations: stage.rotations ?? {},
            objects: stage.objects.map((o: any) => ({ x: o.x, y: o.y, w: o.w, h: o.h }))
          });
        } catch (e) {
          send(res, 500, { error: String(e) });
        }
      });

      server.middlewares.use("/editor/api/save", (req, res) => {
        if (req.method !== "POST") return send(res, 405, { error: "POST only" });
        let def: StageDef;
        try {
          def = resolveStage(req);
        } catch (e) {
          return send(res, 404, { error: String(e) });
        }
        body(req)
          .then(async (payload) => {
            const stage = readJson(def.stagePath);
            const vocab = readJson(def.vocabPath);
            const base = stage.layers.find((l: any) => l.name === "base");
            const fringe = stage.layers.find((l: any) => l.name === "fringe");

            // Mint any new roster tiles into both legend + vocab.
            for (const [char, ref] of Object.entries(payload.legendAdds ?? {})) {
              stage.ascii.legend[char] = ref;
            }
            for (const [char, entry] of Object.entries(payload.vocabAdds ?? {})) {
              vocab.chars[char] = entry;
            }

            // Apply painted cells: ascii char, base ref, clear overlay, collision,
            // and sparse visual rotation (deleted when back to 0).
            if (!stage.rotations) stage.rotations = {};
            for (const c of payload.cells ?? []) {
              const row = stage.ascii.rows[c.y];
              stage.ascii.rows[c.y] = row.slice(0, c.x) + c.char + row.slice(c.x + 1);
              if (base?.data?.[c.y]) base.data[c.y][c.x] = c.ref;
              if (fringe?.data?.[c.y]) fringe.data[c.y][c.x] = null;
              stage.collision[c.y][c.x] = c.blocked ? 1 : 0;
              const rk = `${c.x},${c.y}`;
              if (c.rot) stage.rotations[rk] = c.rot;
              else delete stage.rotations[rk];
            }

            writeJson(def.stagePath, stage);
            writeJson(def.vocabPath, vocab);
            const result = await regenerate(def.script);
            send(res, result.ok ? 200 : 500, result);
          })
          .catch((e) => send(res, 400, { error: String(e) }));
      });

      // Spawns layer save: replace ONLY this floor's editor placements +
      // suppressions in the overlay file (other floors' editor data is left
      // intact), then rerun content:build so the running game hot-reloads. The
      // payload is the FULL desired editor state for the floor — placements in
      // `overlay` (tile coords), base spawns to suppress in `removed`.
      server.middlewares.use("/editor/api/spawns/save", (req, res) => {
        if (req.method !== "POST") return send(res, 405, { error: "POST only" });
        let def: StageDef;
        try {
          def = resolveStage(req);
        } catch (e) {
          return send(res, 404, { error: String(e) });
        }
        const meta = STAGE_META[def.name];
        if (!meta) return send(res, 400, { error: `stage '${def.name}' has no floor/zone mapping — no layers` });
        body(req)
          .then(async (payload) => {
            const { floor, zone } = meta;
            const overlay = readSpawnOverlay();
            // Drop this floor's old entries; keep every other floor's untouched.
            const monsters = overlay.monsters.filter((m) => m.at?.floor !== floor);
            const removed = overlay.removed.filter((r) => r.floor !== floor);
            for (const s of payload.overlay ?? []) {
              monsters.push({ type: s.type, at: { floor, x: s.x, y: s.y }, zone });
            }
            for (const r of payload.removed ?? []) {
              removed.push({ floor, x: r.x, y: r.y });
            }
            writeSpawnOverlay({ monsters, removed });
            const result = await regenerate("content:build");
            send(res, result.ok ? 200 : 500, result);
          })
          .catch((e) => send(res, 400, { error: String(e) }));
      });

      // Generic gathering-node save (?layer=ore, later herbs). Replaces ONLY this
      // floor's overlay nodes + id-suppressions; other floors stay intact. Payload:
      // { nodes:[{id, <field>, x, y, ax, ay}], removed:[<id>] }. Coords are tile
      // centres (x.5/y.5); the server stamps floor + wraps at/approach.
      server.middlewares.use("/editor/api/nodes/save", (req, res) => {
        if (req.method !== "POST") return send(res, 405, { error: "POST only" });
        let def: StageDef;
        try {
          def = resolveStage(req);
        } catch (e) {
          return send(res, 404, { error: String(e) });
        }
        const meta = STAGE_META[def.name];
        if (!meta) return send(res, 400, { error: `stage '${def.name}' has no floor/zone mapping — no layers` });
        const layerId = new URL(req.url ?? "", "http://x").searchParams.get("layer") ?? "";
        const cfg = NODE_LAYERS[layerId];
        if (!cfg) return send(res, 400, { error: `unknown node layer '${layerId}' (have: ${Object.keys(NODE_LAYERS).join(", ")})` });
        body(req)
          .then(async (payload) => {
            const { floor } = meta;
            const overlay = readNodeOverlay(cfg.overlay);
            const nodes = overlay.nodes.filter((n) => n.at?.floor !== floor);
            const removed = overlay.removed.filter((r) => r.floor !== floor);
            for (const n of payload.nodes ?? []) {
              const entry: any = { id: n.id, at: { floor, x: n.x, y: n.y }, approach: { x: n.ax, y: n.ay } };
              if (n[cfg.field] != null) entry[cfg.field] = n[cfg.field];
              nodes.push(entry);
            }
            for (const id of payload.removed ?? []) removed.push({ floor, id });
            writeNodeOverlay(cfg.overlay, cfg.field, { nodes, removed });
            const result = await regenerate("content:build");
            send(res, result.ok ? 200 : 500, result);
          })
          .catch((e) => send(res, 400, { error: String(e) }));
      });
    }
  };
}

export default defineConfig({
  plugins: [editorApi()]
});
