import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { PNG } from "pngjs";

type Dir = "up" | "right" | "down" | "left";
type DrawColor = keyof typeof COLORS;

const repoRoot = process.cwd();
const sourceDir = path.join(repoRoot, "assetsources/gbc/actors");
const publicDir = path.join(repoRoot, "public/sprites/actors");
const artifactDir = path.join(repoRoot, "artifacts/art-new-direction/player-actor-mvp");
const frameW = 20;
const frameH = 24;
const runtimeScale = 2;
const dirs: Dir[] = ["up", "right", "down", "left"];

const COLORS = {
  outline: "#1b1b24",
  boot: "#1d392b",
  pants: "#1c5076",
  tunic: "#2a8297",
  hair: "#7d5b30",
  skin: "#d2ab5e"
} as const;

interface Pose {
  dir: Dir;
  frame: number;
  step: -1 | 0 | 1;
}

mkdirSync(sourceDir, { recursive: true });
mkdirSync(publicDir, { recursive: true });
mkdirSync(artifactDir, { recursive: true });

const source = new PNG({ width: frameW * 4, height: frameH * 4 });
source.data.fill(0);

for (let row = 0; row < dirs.length; row += 1) {
  for (let frame = 0; frame < 4; frame += 1) {
    drawFrame(source, frame * frameW, row * frameH, {
      dir: dirs[row] ?? "down",
      frame,
      step: ([-1, 0, 1, 0][frame] ?? 0) as -1 | 0 | 1
    });
  }
}

const runtime = nearestScale(source, runtimeScale);
writePng(path.join(sourceDir, "player-source.png"), source);
writePng(path.join(sourceDir, "player-runtime.png"), runtime);
writePng(path.join(publicDir, "player-gbc-runtime.png"), runtime);

writePng(path.join(artifactDir, "player-source-contact-sheet.png"), contactSheet(source, frameW, frameH, 3));
writePng(path.join(artifactDir, "player-runtime-contact-sheet.png"), contactSheet(runtime, frameW * runtimeScale, frameH * runtimeScale, 2));
writePng(path.join(artifactDir, "player-grayscale-readability-contact-sheet.png"), grayscaleContact(runtime));

const report = [
  "# GBC Player Actor MVP Implementation Report",
  "",
  "Status: implementation assets generated; validator and gameplay proof update this directory.",
  "Started from HEAD: 5682e7f2",
  "",
  "## Actor Contract",
  "",
  "- Source: `assetsources/gbc/actors/player-source.png`",
  "- Runtime: `assetsources/gbc/actors/player-runtime.png`",
  "- Public runtime: `public/sprites/actors/player-gbc-runtime.png`",
  "- Sheet: 4 rows (`walk_up`, `walk_right`, `walk_down`, `walk_left`) by 4 frames.",
  "- Source frame: 20x24, exact 2x nearest runtime frame: 40x48.",
  "- Palette: 6 declared opaque colors plus transparency.",
  "- Runtime family: `playerGbc`; legacy `knight`/`caster` NPC users stay on `public/player-sheet.png`.",
  "",
  "## Proof Links",
  "",
  "- Validator reports: `gbc-validator-report.md` and `gbc-validator-report.json` after `npm run assets:gbc:check`.",
  "- Source contact: `player-source-contact-sheet.png`",
  "- Runtime contact: `player-runtime-contact-sheet.png`",
  "- Grayscale contact: `player-grayscale-readability-contact-sheet.png`",
  "- Gameplay screenshots and trace are generated by `tests/e2e/player-actor-mvp.spec.ts`."
].join("\n");
writeFileSync(path.join(artifactDir, "IMPLEMENTATION_REPORT.md"), `${report}\n`);

console.log("Wrote GBC player actor source/runtime sheets and proof contacts.");

function drawFrame(sheet: PNG, ox: number, oy: number, pose: Pose): void {
  const px = (x: number, y: number, color: DrawColor): void => setPixel(sheet, ox + x, oy + y, color);
  drawHead(px, pose);
  drawBody(px, pose);
  drawLegs(px, pose);
}

function drawHead(px: (x: number, y: number, color: DrawColor) => void, pose: Pose): void {
  if (pose.dir === "up") {
    rect(px, 6, 1, 8, 7, "outline");
    rect(px, 7, 2, 6, 5, "hair");
    rect(px, 8, 6, 4, 2, "skin");
    return;
  }

  rect(px, 6, 1, 8, 7, "outline");
  rect(px, 7, 2, 6, 2, "hair");
  rect(px, 7, 4, 6, 4, "skin");
  px(7, 5, "outline");
  px(12, 5, "outline");
  if (pose.dir === "right") {
    px(13, 4, "skin");
    px(13, 5, "outline");
    px(6, 5, "hair");
  } else if (pose.dir === "left") {
    px(6, 4, "skin");
    px(6, 5, "outline");
    px(13, 5, "hair");
  } else {
    px(9, 7, "outline");
    px(10, 7, "outline");
  }
}

function drawBody(px: (x: number, y: number, color: DrawColor) => void, pose: Pose): void {
  rect(px, 6, 8, 8, 8, "outline");
  rect(px, 7, 9, 6, 6, "tunic");
  if (pose.dir === "right") {
    rect(px, 5, 10, 2, 5, "outline");
    px(5, 14, "skin");
  } else if (pose.dir === "left") {
    rect(px, 13, 10, 2, 5, "outline");
    px(14, 14, "skin");
  } else if (pose.dir === "down") {
    rect(px, 5, 10, 1, 5, "outline");
    rect(px, 14, 10, 1, 5, "outline");
    px(5, 14, "skin");
    px(14, 14, "skin");
  } else {
    rect(px, 5, 10, 1, 5, "outline");
    rect(px, 14, 10, 1, 5, "outline");
  }
  if (pose.dir === "up") {
    rect(px, 8, 8, 4, 2, "hair");
  }
}

function drawLegs(px: (x: number, y: number, color: DrawColor) => void, pose: Pose): void {
  const a = pose.step;
  const b = (-pose.step) as -1 | 0 | 1;
  if (pose.dir === "right") {
    leg(px, 8 + Math.max(0, b), 16, b);
    leg(px, 11 + Math.max(0, a), 16, a);
    return;
  }
  if (pose.dir === "left") {
    leg(px, 11 - Math.max(0, b), 16, -b as -1 | 0 | 1);
    leg(px, 8 - Math.max(0, a), 16, -a as -1 | 0 | 1);
    return;
  }
  leg(px, 7, 16, a);
  leg(px, 11, 16, b);
}

function leg(px: (x: number, y: number, color: DrawColor) => void, x: number, y: number, step: -1 | 0 | 1): void {
  const lowerY = step === 0 ? y + 3 : y + 2;
  const footY = 22;
  const footX = x + step;
  rect(px, x, y, 2, 5, "outline");
  rect(px, x, y, 2, 3, "pants");
  rect(px, footX, lowerY, 2, footY - lowerY + 1, "outline");
  rect(px, footX, lowerY, 2, Math.max(1, footY - lowerY), "pants");
  rect(px, footX - (step < 0 ? 1 : 0), footY, 3, 1, "boot");
}

function rect(px: (x: number, y: number, color: DrawColor) => void, x: number, y: number, w: number, h: number, color: DrawColor): void {
  for (let yy = y; yy < y + h; yy += 1) for (let xx = x; xx < x + w; xx += 1) px(xx, yy, color);
}

function setPixel(png: PNG, x: number, y: number, color: DrawColor): void {
  if (x < 0 || y < 0 || x >= png.width || y >= png.height) return;
  const rgb = hexToRgb(COLORS[color]);
  const i = (y * png.width + x) * 4;
  png.data[i] = rgb.r;
  png.data[i + 1] = rgb.g;
  png.data[i + 2] = rgb.b;
  png.data[i + 3] = 255;
}

function nearestScale(src: PNG, scale: number): PNG {
  const out = new PNG({ width: src.width * scale, height: src.height * scale });
  out.data.fill(0);
  for (let y = 0; y < out.height; y += 1) {
    for (let x = 0; x < out.width; x += 1) {
      copyPixel(src, Math.floor(x / scale), Math.floor(y / scale), out, x, y);
    }
  }
  return out;
}

function contactSheet(src: PNG, cellW: number, cellH: number, scale: number): PNG {
  const gap = 2;
  const cols = 4;
  const rows = 4;
  const out = new PNG({ width: cols * cellW * scale + (cols + 1) * gap, height: rows * cellH * scale + (rows + 1) * gap });
  fill(out, "#263238");
  for (let row = 0; row < rows; row += 1) {
    for (let col = 0; col < cols; col += 1) {
      const dx = gap + col * (cellW * scale + gap);
      const dy = gap + row * (cellH * scale + gap);
      blitNearest(src, out, col * cellW, row * cellH, cellW, cellH, dx, dy, scale);
    }
  }
  return out;
}

function grayscaleContact(src: PNG): PNG {
  const contact = contactSheet(src, frameW * runtimeScale, frameH * runtimeScale, 2);
  for (let i = 0; i < contact.data.length; i += 4) {
    if ((contact.data[i + 3] ?? 0) === 0) continue;
    const lum = Math.round((contact.data[i] ?? 0) * 0.299 + (contact.data[i + 1] ?? 0) * 0.587 + (contact.data[i + 2] ?? 0) * 0.114);
    contact.data[i] = lum;
    contact.data[i + 1] = lum;
    contact.data[i + 2] = lum;
  }
  return contact;
}

function blitNearest(src: PNG, dst: PNG, sx: number, sy: number, w: number, h: number, dx: number, dy: number, scale: number): void {
  for (let y = 0; y < h * scale; y += 1) {
    for (let x = 0; x < w * scale; x += 1) {
      copyPixel(src, sx + Math.floor(x / scale), sy + Math.floor(y / scale), dst, dx + x, dy + y);
    }
  }
}

function copyPixel(from: PNG, fromX: number, fromY: number, to: PNG, toX: number, toY: number): void {
  const fromIndex = (fromY * from.width + fromX) * 4;
  const toIndex = (toY * to.width + toX) * 4;
  to.data[toIndex] = from.data[fromIndex] ?? 0;
  to.data[toIndex + 1] = from.data[fromIndex + 1] ?? 0;
  to.data[toIndex + 2] = from.data[fromIndex + 2] ?? 0;
  to.data[toIndex + 3] = from.data[fromIndex + 3] ?? 0;
}

function fill(png: PNG, hex: string): void {
  const rgb = hexToRgb(hex);
  for (let i = 0; i < png.data.length; i += 4) {
    png.data[i] = rgb.r;
    png.data[i + 1] = rgb.g;
    png.data[i + 2] = rgb.b;
    png.data[i + 3] = 255;
  }
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  return {
    r: Number.parseInt(hex.slice(1, 3), 16),
    g: Number.parseInt(hex.slice(3, 5), 16),
    b: Number.parseInt(hex.slice(5, 7), 16)
  };
}

function writePng(file: string, png: PNG): void {
  writeFileSync(file, PNG.sync.write(png));
}
